version: '3.9'
services:
  react1:
    build: ./client  # Specify the path to the React app's Dockerfile
    container_name: r2
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
    stdin_open: true
    tty: true

  mysql1:
    image: mysql:5.7
    container_name: db2
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-padmin"]
      timeout: 20s # Timeout for each health checking.
      retries: 10 # Hou many times retries.  

  node1:
    build: ./server  # Specify the path to the server's Dockerfile
    container_name: n2
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app/server
    environment:              #  addition enviorment info to set up enviorment
      - DB_HOST=mysql1
      - DB_USER=root
      - DB_PASSWORD=admin 
    depends_on:
      mysql1:
        condition: service_healthy
    stdin_open: true
    tty: true

